sudo: required
services:
  - docker

before_install:
  - docker build -t yoshijifujiwara/react-ci -f Dockerfile.dev .

script:
  - docker run yoshijifujiwara/react-ci npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "react-ci"
  env: "ReactCi-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-ap-northeast-1-961014738960",
  bucket_path: "react-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"